CREATE SEQUENCE MUSERGROUP_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MUSERGROUPMENU_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MUSER_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MDECLINECODE_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MUNIT_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MSECTOR_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MDEBITUR_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MRMGROUP_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MRM_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE MCURRENCY_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TTARGETRMGROUP_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TTARGETRM_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPIPELINE_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPIPELINEPART_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPIPELINEPARTAGENT_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TMEMO_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPORTO_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPORTOPART_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPORTOPARTAGENT_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPORTOPARTDEBT_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPORTOPAYMENT_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPORTOINVOICE_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE TPORTOPAYSCHEDULE_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;


CREATE TABLE MSYSPARAM  (
	MSYSPARAMPK INTEGER NOT NULL PRIMARY KEY, 
	PARAMNAME CHAR(50) NOT NULL , 
	PARAMVALUE CHAR(100) DEFAULT '',
	PARAMDESC CHAR(100) DEFAULT '', 
	ISMASKED CHARACTER(1) DEFAULT '',
	PARAMGROUP CHAR(50) DEFAULT '', 	
	ORDERNO INTEGER DEFAULT 0,
	UPDATEDBY CHAR(50) DEFAULT '',
	LASTUPDATED TIMESTAMP
);

CREATE TABLE MMENU (
	MMENUPK INTEGER NOT NULL PRIMARY KEY, 
	MENUORDERNO INTEGER DEFAULT 0 , 
	MENUGROUP CHAR(40) DEFAULT '' ,
	MENUGROUPICON CHAR(50) DEFAULT '',
	MENUSUBGROUP CHAR(40) DEFAULT '' ,
	MENUSUBGROUPICON CHAR(50) DEFAULT '',
	MENUNAME CHAR(100) DEFAULT '' ,
	MENUICON CHAR(50) DEFAULT '',
	MENUPATH CHAR(100) DEFAULT '' , 
	MENUPARAMNAME CHAR(10) DEFAULT '' , 
	MENUPARAMVALUE CHAR(30) DEFAULT '' 
);

CREATE TABLE MUSERGROUP  (
	MUSERGROUPPK INTEGER NOT NULL PRIMARY KEY , 
	USERGROUPCODE CHAR(20) DEFAULT '' , 
	USERGROUPNAME CHAR(40) DEFAULT '' , 
	USERGROUPDESC CHAR(100) DEFAULT '' , 
	UPDATEDBY CHAR(15) DEFAULT '',
	LASTUPDATED TIMESTAMP
);

CREATE TABLE MUSERGROUPMENU (
	MUSERGROUPMENUPK INTEGER NOT NULL PRIMARY KEY , 
	MUSERGROUPFK INTEGER NOT NULL , 
	MMENUFK INTEGER NOT NULL ); 
ALTER TABLE MUSERGROUPMENU
	ADD CONSTRAINT MUSERGROUPMENU_FK1 FOREIGN KEY
		(MUSERGROUPFK)
	REFERENCES MUSERGROUP
		(MUSERGROUPPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;
ALTER TABLE MUSERGROUPMENU
	ADD CONSTRAINT MUSERGROUPMENU_FK2 FOREIGN KEY
		(MMENUFK)
	REFERENCES MMENU
		(MMENUPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;
		 
CREATE TABLE MUSER (
	MUSERPK INTEGER NOT NULL PRIMARY KEY , 
	MUSERGROUPFK INTEGER NOT NULL, 
	USERID CHAR(15) DEFAULT '', 
	USERNAME CHAR(40) DEFAULT '', 
	PASSWORD CHAR(70) DEFAULT '', 	
	EMAIL CHAR(100) DEFAULT '', 
	UPDATEDBY CHAR(15) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE MUSER
	ADD CONSTRAINT MUSER_FK1 FOREIGN KEY
		(MUSERGROUPFK)
	REFERENCES MUSERGROUP
		(MUSERGROUPPK)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

CREATE TABLE TSCHEDULER  (
	TSCHEDULERPK INTEGER NOT NULL PRIMARY KEY, 
	SCHEDULERNAME CHAR(30) DEFAULT '' , 
	SCHEDULERGROUP CHAR(30) DEFAULT '' , 
	SCHEDULERDESC VARCHAR(200) DEFAULT '' , 
	SCHEDULERSTATUS CHAR(3) DEFAULT '' , 
	SCHEDULERREPEATTYPE CHAR(10) DEFAULT '' , 
	REPEATINTERVAL INTEGER DEFAULT 0 , 
	JOBCLASS CHAR(70) DEFAULT '', 
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
); 

CREATE TABLE TCOUNTERENGINE  (
	COUNTERNAME CHAR(30) DEFAULT '' , 
	LASTCOUNTER INTEGER DEFAULT 0 ); 

CREATE TABLE MDECLINECODE  (
	MDECLINECODEPK INTEGER NOT NULL PRIMARY KEY , 
	DECLINECODE CHAR(3) DEFAULT '' , 
	DECLINEDESC CHAR(70) DEFAULT '' , 	
	LASTUPDATED TIMESTAMP, 
	UPDATEDBY CHAR(15) DEFAULT ''
);
	
CREATE TABLE MUNIT (
	MUNITPK INTEGER NOT NULL PRIMARY KEY, 
	UNITCODE CHAR(5) DEFAULT '',
	UNITNAME CHAR(50) DEFAULT '',
	UNITCOSTCENTER CHAR(10) DEFAULT '',
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);

CREATE TABLE MSECTOR (
	MSECTORPK INTEGER NOT NULL PRIMARY KEY, 
	SECTORNAME CHAR(50) DEFAULT '',
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);

CREATE TABLE MDEBITUR (
	MDEBITURPK INTEGER NOT NULL PRIMARY KEY , 
	DEBITUR CHAR(100) DEFAULT '',
	OFFICEPHONE CHAR(40) DEFAULT '',
	OFFICEFAX CHAR(40) DEFAULT '',
	OFFICEEMAIL CHAR(100) DEFAULT '',
	OFFICEADDRESS CHAR(200) DEFAULT '',
	DIRNAME CHAR(40) DEFAULT '',
	DIRPHONE CHAR(40) DEFAULT '',
	DIREMAIL CHAR(40) DEFAULT '',
	KOLEKTIBILITAS CHAR(1) DEFAULT '', /* ADD */
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);

CREATE TABLE MRMGROUP (
	MRMGROUPPK INTEGER NOT NULL PRIMARY KEY , 
	RMGROUPCODE CHAR(10) DEFAULT '',
	RMGROUPNAME CHAR(40) DEFAULT '',
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);

CREATE TABLE MRM (
	MRMPK INTEGER NOT NULL PRIMARY KEY, 
	MRMGROUPFK INTEGER NOT NULL,
	RMID CHAR(10) DEFAULT '',
	RMNAME CHAR(40) DEFAULT '',
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE MRM
	ADD CONSTRAINT MRM_FK1 FOREIGN KEY
		(MRMGROUPFK)
	REFERENCES MRMGROUP
		(MRMGROUPPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;

CREATE TABLE MCURRENCY (
	MCURRENCYPK INTEGER NOT NULL PRIMARY KEY , 
	CURRENCYCODE CHAR(5) DEFAULT '',
	COUNTRY CHAR(40) DEFAULT '',
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);

CREATE TABLE MAGENTTYPE (
	MAGENTTYPEPK INTEGER NOT NULL PRIMARY KEY , 
	AGENTCODE CHAR(5) DEFAULT '',
	DESCRIPTION CHAR(100) DEFAULT '',
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);

CREATE TABLE TTARGETRMGROUP  (
	TTARGETRMGROUPPK INTEGER NOT NULL PRIMARY KEY , 
	MRMGROUPFK INTEGER NOT NULL,
	TARGETYEAR CHAR(4) DEFAULT '',
	TARGETAMOUNT DECIMAL(17,0) DEFAULT 0,
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TTARGETRMGROUP
	ADD CONSTRAINT TTARGETRMGROUP_FK1 FOREIGN KEY
		(MRMGROUPFK)
	REFERENCES MRMGROUP
		(MRMGROUPPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;
	
CREATE TABLE TTARGETRM  (
	TTARGETRMPK INTEGER NOT NULL PRIMARY KEY , 
	MRMGROUPFK INTEGER NOT NULL,
	MRMFK INTEGER NOT NULL,
	TARGETYEAR CHAR(4) DEFAULT '',
	TARGETAMOUNT DECIMAL(17,0) DEFAULT 0,
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TTARGETRM
	ADD CONSTRAINT TTARGETRM_FK1 FOREIGN KEY
		(MRMGROUPFK)
	REFERENCES MRMGROUP
		(MRMGROUPPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;
ALTER TABLE TTARGETRM
	ADD CONSTRAINT TTARGETRM_FK2 FOREIGN KEY
		(MRMFK)
	REFERENCES MRM
		(MRMPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;
	
CREATE TABLE TPIPELINE  (
	TPIPELINEPK INTEGER NOT NULL PRIMARY KEY , 
	MDEBITURFK INTEGER NOT NULL,
	MSECTORFK INTEGER NOT NULL,
	MUNITFK INTEGER NOT NULL,
	MRMFK INTEGER NOT NULL,
	REGID CHAR(13) DEFAULT '',
	REGTIME TIMESTAMP,
	PROJECT CHAR(100) DEFAULT '',
	RMCREDIT CHAR(40) DEFAULT '',	
	CURRENCY CHAR(5) DEFAULT '',
	PROJECTAMOUNT DECIMAL(17,0) DEFAULT 0,
	CREDITFACILITY DECIMAL(17,0) DEFAULT 0,
	SELFPORTION DECIMAL(17,0) DEFAULT 0,
	FEEPERCENT DECIMAL(4,1) DEFAULT 0,
	FEEAMOUNT DECIMAL(17,0) DEFAULT 0,
	TARGETPK DATE,
	NOTES CHAR(200) DEFAULT '',
	STATUS CHAR(2) DEFAULT '',	
	
	TRANCHE CHAR(40) DEFAULT '', /* ADD */
	
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPIPELINE
	ADD CONSTRAINT TPIPELINE_FK1 FOREIGN KEY
		(MDEBITURFK)
	REFERENCES MDEBITUR
		(MDEBITURPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;
ALTER TABLE TPIPELINE
	ADD CONSTRAINT TPIPELINE_FK2 FOREIGN KEY
		(MSECTORFK)
	REFERENCES MSECTOR
		(MSECTORPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;
ALTER TABLE TPIPELINE
	ADD CONSTRAINT TPIPELINE_FK3 FOREIGN KEY
		(MUNITFK)
	REFERENCES MUNIT
		(MUNITPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;
ALTER TABLE TPIPELINE
	ADD CONSTRAINT TPIPELINE_FK4 FOREIGN KEY
		(MRMFK)
	REFERENCES MRM
		(MRMPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;

CREATE TABLE TPIPELINEPART  (
	TPIPELINEPARTPK INTEGER NOT NULL PRIMARY KEY , 
	TPIPELINEFK INTEGER NOT NULL,
	PARTICIPANTNAME CHAR(100) DEFAULT '',
	PORTIONPERCENT DECIMAL(4,1) DEFAULT 0,
	PORTIONAMOUNT DECIMAL(17,0) DEFAULT 0,
	
	CURRENCY CHAR(5) DEFAULT '', /* ADD */
	KIPOKOK DECIMAL(17,0) DEFAULT 0, /* ADD */
	KIIDC DECIMAL(17,0) DEFAULT 0, /* ADD */
	KMK DECIMAL(17,0) DEFAULT 0, /* ADD */
	NCL DECIMAL(17,0) DEFAULT 0, /* ADD */
	PICNAME CHAR(30) DEFAULT '', /* ADD */
	PICHP CHAR(20) DEFAULT '', /* ADD */
	PICEMAIL CHAR(100) DEFAULT '', /* ADD */
	ISSELF CHAR(1) DEFAULT '', /* ADD */ /* Y UNTUK BNI, N UNTUK PARTICIPANT LAIN */
	
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPIPELINEPART
	ADD CONSTRAINT TPIPELINEPART_FK1 FOREIGN KEY
		(TPIPELINEFK)
	REFERENCES TPIPELINE
		(TPIPELINEPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

/* NEW TABLE */
CREATE TABLE TPIPELINEPARTAGENT  (
	TPIPELINEPARTAGENTPK INTEGER NOT NULL PRIMARY KEY , 
	TPIPELINEPARTFK INTEGER NOT NULL, 
	MAGENTTYPEFK INTEGER NOT NULL,	
	CURRENCY CHAR(5) DEFAULT '',
	FEEAMOUNT DECIMAL(17,0) DEFAULT 0,
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPIPELINEPARTAGENT
	ADD CONSTRAINT TPIPELINEPARTAGENT_FK1 FOREIGN KEY
		(TPIPELINEPARTFK)
	REFERENCES TPIPELINEPART
		(TPIPELINEPARTPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;
ALTER TABLE TPIPELINEPARTAGENT
	ADD CONSTRAINT TPIPELINEPARTAGENT_FK2 FOREIGN KEY
		(MAGENTTYPEFK)
	REFERENCES MAGENTTYPE
		(MAGENTTYPEPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;

	
CREATE TABLE TMEMO  (
	TMEMOPK INTEGER NOT NULL PRIMARY KEY, 
	TPIPELINEFK INTEGER NOT NULL , 
	MEMO CHAR(200) DEFAULT '' , 
	CREATEDTIME TIMESTAMP DEFAULT NULL , 
	CREATEDBY CHAR(15) DEFAULT ''
); 
ALTER TABLE TMEMO
	ADD CONSTRAINT TMEMO_FK1 FOREIGN KEY
		(TPIPELINEFK)
	REFERENCES TPIPELINE
		(TPIPELINEPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;
	
CREATE TABLE TPORTO  (
	TPORTOPK INTEGER NOT NULL PRIMARY KEY , 
	MSECTORFK INTEGER NOT NULL,
	MUNITFK INTEGER NOT NULL,
	REGID CHAR(13) DEFAULT '',
	REGTIME TIMESTAMP,
	DEBITUR CHAR(100) DEFAULT '',
	OFFICEPHONE CHAR(40) DEFAULT '',
	OFFICEFAX CHAR(40) DEFAULT '',
	OFFICEEMAIL CHAR(100) DEFAULT '',
	OFFICEADDRESS CHAR(200) DEFAULT '',
	DIRNAME CHAR(40) DEFAULT '',
	DIRPHONE CHAR(40) DEFAULT '',
	DIREMAIL CHAR(40) DEFAULT '',
	PROJECT CHAR(100) DEFAULT '',
	RMGROUPCODE CHAR(10) DEFAULT '',
	RMID CHAR(10) DEFAULT '',	
	RMNAME CHAR(40) DEFAULT '',	
	RMCREDIT CHAR(40) DEFAULT '',	
	CURRENCY CHAR(5) DEFAULT '',
	PROJECTAMOUNT DECIMAL(17,0) DEFAULT 0,
	CREDITFACILITY DECIMAL(17,0) DEFAULT 0,
	SELFPORTION DECIMAL(17,0) DEFAULT 0,
	FEEPERCENT DECIMAL(4,1) DEFAULT 0,
	FEEAMOUNT DECIMAL(17,0) DEFAULT 0,
	TARGETPK DATE,
	PORTODATE DATE,
	
	SUKUBUNGA CHAR(40) DEFAULT '', /* ADD */
	TRANCHE CHAR(40) DEFAULT '', /* ADD */
	ISRESTUCTPROYEKSI CHAR(1) DEFAULT '', /* ADD */
	ISRESTUCTDEBITUR CHAR(1) DEFAULT '', /* ADD */
	NOPK CHAR(20) DEFAULT '', /* ADD */
	SIGNDATE DATE, /* ADD */
	DUEDATE DATE, /* ADD */
	LASTOUTSTANDING DECIMAL(17,0) DEFAULT 0, /* UNTUK BNI */
	LASTINCOMEFEE DECIMAL(17,0) DEFAULT 0, /* ADD */
	LASTINCOMEBUNGA DECIMAL(17,0) DEFAULT 0, /* ADD */
	
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPORTO
	ADD CONSTRAINT TPORTO_FK1 FOREIGN KEY
		(MSECTORFK)
	REFERENCES MSECTOR
		(MSECTORPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;
ALTER TABLE TPORTO
	ADD CONSTRAINT TPORTO_FK2 FOREIGN KEY
		(MUNITFK)
	REFERENCES MUNIT
		(MUNITPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;

CREATE TABLE TPORTOPART  (
	TPORTOPARTPK INTEGER NOT NULL PRIMARY KEY , 
	TPORTOFK INTEGER NOT NULL,
	PARTICIPANTNAME CHAR(100) DEFAULT '',
	PORTIONPERCENT DECIMAL(4,1) DEFAULT 0,
	PORTIONAMOUNT DECIMAL(17,0) DEFAULT 0,
	
	CURRENCY CHAR(5) DEFAULT '', /* ADD */
	KIPOKOK DECIMAL(17,0) DEFAULT 0, /* ADD */
	KIIDC DECIMAL(17,0) DEFAULT 0, /* ADD */
	KMK DECIMAL(17,0) DEFAULT 0, /* ADD */
	NCL DECIMAL(17,0) DEFAULT 0, /* ADD */	
	OSKIPOKOK DECIMAL(17,0) DEFAULT 0, /* ADD */
	OSKIIDC DECIMAL(17,0) DEFAULT 0, /* ADD */
	OSKMK DECIMAL(17,0) DEFAULT 0, /* ADD */
	OSNCL DECIMAL(17,0) DEFAULT 0, /* ADD */	
	PICNAME CHAR(30) DEFAULT '', /* ADD */
	PICHP CHAR(20) DEFAULT '', /* ADD */
	PICEMAIL CHAR(100) DEFAULT '', /* ADD */
	ISSELF CHAR(1) DEFAULT '', /* ADD */ /* Y UNTUK BNI, N UNTUK PARTICIPANT LAIN */
	
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPORTOPART
	ADD CONSTRAINT TPORTOPART_FK1 FOREIGN KEY
		(TPORTOFK)
	REFERENCES TPORTO
		(TPORTOPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;
	
/* NEW TABLE */
CREATE TABLE TPORTOPARTAGENT  (
	TPORTOPARTAGENTPK INTEGER NOT NULL PRIMARY KEY , 
	TPORTOPARTFK INTEGER NOT NULL, 
	MAGENTTYPEFK INTEGER NOT NULL,	
	CURRENCY CHAR(5) DEFAULT '',
	FEEAMOUNT DECIMAL(17,0) DEFAULT 0,
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPORTOPARTAGENT
	ADD CONSTRAINT TPORTOPARTAGENT_FK1 FOREIGN KEY
		(TPORTOPARTFK)
	REFERENCES TPORTOPART
		(TPORTOPARTPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;
ALTER TABLE TPORTOPARTAGENT
	ADD CONSTRAINT TPORTOPARTAGENT_FK2 FOREIGN KEY
		(MAGENTTYPEFK)
	REFERENCES MAGENTTYPE
		(MAGENTTYPEPK)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION;

/* NEW TABLE */
CREATE TABLE TPORTOPAYSCHEDULE  (
	TPORTOPAYSCHEDULEPK INTEGER NOT NULL PRIMARY KEY , 
	TPORTOFK INTEGER NOT NULL,
	PAYTYPE CHAR(1) DEFAULT '', /* 1:POKOK, 2:BUNGA, 3:FEE */
	MONTHSCHEDULE CHAR(24) DEFAULT '', /* EX: JANUARI, MARET, JUNI -> 1;3;6 */
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPORTOPAYSCHEDULE
	ADD CONSTRAINT TPORTOPAYSCHEDULE_FK1 FOREIGN KEY
		(TPORTOFK)
	REFERENCES TPORTO
		(TPORTOPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

/* NEW TABLE */
CREATE TABLE TPORTOINVOICE (
	TPORTOINVOICEPK INTEGER NOT NULL PRIMARY KEY , 
	TPORTOFK INTEGER NOT NULL,
	INVOICENO CHAR(20) DEFAULT '',
	PAYTYPE CHAR(1) DEFAULT '', /* 1:POKOK, 2:BUNGA, 3:FEE */
	CURRENCY CHAR(5) DEFAULT '',
	INVOICEAMOUNT DECIMAL(17,0) DEFAULT 0, /* SEMENTARA INPUT MANUAL, LALU DATA INVOICE INI DIGENARET SURAT INVOICENYA DALAM BENTUK PDF */
	INVOICEDATE DATE,
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPORTOINVOICE
	ADD CONSTRAINT TPORTOINVOICE_FK1 FOREIGN KEY
		(TPORTOFK)
	REFERENCES TPORTO
		(TPORTOPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;
	
/* NEW TABLE */
CREATE TABLE TPORTOPAYMENT (
	TPORTOPAYSCHEDULEPK INTEGER NOT NULL PRIMARY KEY , 
	TPORTOINVOICEFK INTEGER NOT NULL,
	PAYTYPE CHAR(1) DEFAULT '', /* 1:POKOK, 2:BUNGA, 3:FEE */
	CURRENCY CHAR(5) DEFAULT '',
	PAYAMOUNT DECIMAL(17,0) DEFAULT 0,
	PAYDATE DATE,
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPORTOPAYMENT
	ADD CONSTRAINT TPORTOPAYMENT_FK1 FOREIGN KEY
		(TPORTOINVOICEFK)
	REFERENCES TPORTOINVOICE
		(TPORTOINVOICEPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

/* NEW TABLE */
CREATE TABLE TPORTOPARTDEBT  (
	TPORTOPARTDEBTPK INTEGER NOT NULL PRIMARY KEY , 
	TPORTOPARTFK INTEGER , 
	CURRENCY CHAR(5) DEFAULT '',
	KIPOKOK DECIMAL(17,0) DEFAULT 0,
	KIIDC DECIMAL(17,0) DEFAULT 0,
	KMK DECIMAL(17,0) DEFAULT 0,
	NCL DECIMAL(17,0) DEFAULT 0,
	DEBTAMOUNT  DECIMAL(17,0) DEFAULT 0, /* AKUMULASI POKOK,IDC,KMK,NCL */
	DEBTDATE DATE,
	UPDATEDBY CHAR(30) DEFAULT '',
	LASTUPDATED TIMESTAMP
);
ALTER TABLE TPORTOPARTDEBT
	ADD CONSTRAINT TPORTOPARTDEBT_FK1 FOREIGN KEY
		(TPORTOPARTFK)
	REFERENCES TPORTOPART
		(TPORTOPARTPK)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;